### ISSUE TITLE
PrivateServerKey appearance delay

### ISSUE THREAD

**Issue by blinkybool** [metauni/metaportal#14]
While making the Moonlight Forest pocket, I found that the PrivateServerKey StringValue could sometimes take up to 13 seconds to appear under `workspace`. I was trying to make persistence for metaboardv1 work with pockets, but the PrivateServerKey sometimes isn't there in time for the restoreAll code to find it (it's needed as a prefix for keys at the moment).

This is fixed by a WaitForChild, but might be worth investigating what takes so long.

**Comment by dmurfet** [comment]
It's probably inappropriate for metaboard, which is meant in principle for other people to use, to assume that a private server without an owner (= one made by ReserveServer, what we call a pocket) must have some random thing in workspace called `PrivateServerId`.

My suggestion is instead is to make this explicitly a metaboard / metaportal integration. So metaboard checks for `MetaPortal` in `ReplicatedStorage` (along the lines of what we discussed some weeks ago). If it exists, metaboard `WaitForChild`s on a stringvalue inside that folder `PrivateServerId`. If it doesn't exist, we assume the user doesn't care about metaportal and there is nothing special about the current experience or its key format.

**Comment by blinkybool** [comment]
Sounds sensible. At the same time I think we should move towards using a separate datastore rather than prefixing keys. So if MetaPortal is there, then you make use of the datastore called `persistence/ps12345` or something.

**Comment by blinkybool** [comment]
@dmurfet Suppose you open a pocket within Roblox Studio. Is it possible to recover the private server key somehow? Or should boards just not load in that scenario. If we don't load boards, how do I differentiate between being in a pocket place that shouldn't load boards, vs being in the main TRS place, which should?

Edit: nevermind I found this
```lua
local function isPrivateServer()
	return game.PrivateServerId ~= ""
end
```

**Comment by dmurfet** [comment]
I'm not sure what state of mind your edit reflects, but there is a difference between private servers created through the webpage (which correspond to those in which the function you quote returns `true`) and private servers created through `ReserveServer` via the `TeleportService` API. The latter are those in which `isPocket` returns `true` (this function appears in a few places, in particular in `v0` metaboard, I think you would have seen it).

Your question doesn't parse, because a pocket is not just a place, it is a place plus access code, so there is no way in Studio to be "in" a particular pocket (at present, I suppose we could attempt this by allowing you to specify it on the command line or in some other way, but I haven't had any reason to do that).

**Comment by blinkybool** [comment]
Yep I understand the pocket/place distinction now.
Regarding private servers, I think I get it now too. Am I correct in that the only defined behaviour we have for persistence is in the following two scenarios?
1. Not a private server (use normal keys)
2. In a private server + isPocket (use prefixed keys, or use a different dataStore in v1's case)

The third scenario being isPrivateServer but no isPocket. In the third scenario (which maybe never happens by design), what should persistence do? Load nothing? Is there any reason not to treat it just like a pocket and store to a datastore with the private server key? Can you go back to the same webpage-private-server if you leave it?

Also I do not see isPocket *anywhere* in the v0 code.

Also why do we use a `PrivateServerKey` StringValue? Why not `game.PrivateServerId`? What's the difference?

**Comment by dmurfet** [comment]
The scenario list is correct. In the case of a private server I'm not sure, but the `PrivateServerId` is in that case a unique identifier and could be used as the basis for creating a key. That should probably be the default behaviour.

`PrivateServerKey` is `game.PlaceId-<PocketCounter>` see the following code from https://github.com/metauni/metaportal/blob/main/src/server/MetaPortal.lua. Of course the `PlaceId` is redundant if you're *in* the pocket since you can just get it with `game.PlaceId` but the point is that if you want to access that data elsewhere, the key needs to be a unique identifier of a pocket. The way I chose to do it is that e.g. `Alpha Cove 11` is identified by `8465004288-11`. There is another alternative (which is to index it by the placeId and access code returned by `ReserveServer` when the pocket is created, but as these concatenated is longer than the max length of a DataStore key some kind of secondary step of hashing that to a short value would be involved, and I decided against it).

<img width="589" alt="Screen Shot 2022-07-25 at 12 27 05 pm" src="https://user-images.githubusercontent.com/320329/180681279-f9e67fa4-c789-4845-ac8f-38c787d55539.png">

The complexity lies in that you can't just query the Roblox API for the `PocketCounter` (nor for the AccessCode IIRC). It is passed in with the teleport data for every player coming to the pocket, so `metaportal` grabs that and stores it in the `PrivateServerKey` (you could say the `PlaceId` shouldn't be there, but I addressed this already above). This is the reason why other services should wait for `metaportal` to process the incoming teleport data so that the pocket "knows who it is".

**Comment by blinkybool** [comment]
Okay that makes sense.

I need to know how to recognise the scenario when you open a pocket-template-place in Roblox Studio for persistence, in which case it should not load any boards. The hard part I think is distinguishing between opening the main TRS-place, and opening some pocket-template-place, because you do want to load the normal boards in Studio when you open the main TRS place, right? metaportal exists in both the TRS-place and every pocket-template-place, right? Also game.PrivateServerId will be "" in both the TRS place and every pocket-template-place, right?

**Comment by dmurfet** [comment]
Correct. At the moment when you load a pocket place in Studio you'll see the boards associated to those PersistIds by TRS (as you would expect). That's surprising and a bit scary, I agree. However it's hard to distinguish a pocket in Studio. One way would be just to check if your PlaceId appears in `Config.PlaceIdOfPockets` in metaportal.

This in any case shouldn't be in the metaportal distribution itself since it's specific to TRS, and I am likely to put a ModuleScript in `MetaPortal` within `ReplicatedStorage` with `PlaceIdOfPockets` in it, which metaportal looks for on startup. 

Pockets have lots of pocket-specific stuff in them (like the Return portal, Start part etc) that we could look for to determine pocket-ness. But all of these are in some sense less convincing than looking for `MetaPortal > LocalConfig` and checking `PlaceIdOfPockets` inside that. So my proposal is that I patch metaportal today to do that, and then in TRS and all pockets there will be such a `LocalConfig` and you can look for that in Studio using metaboard.

Note that as we discussed, this `MetaPortal` folder would be created manually, so you can check for it on startup without `WaitForChild`.

**Comment by dmurfet** [comment]
I think this is no longer a problem
